const fs = require('fs');

// Common vocabulary words to add
const vocabList = [
  { word: 'important', meaning: '重要的' },
  { word: 'challenge', meaning: '挑战' },
  { word: 'success', meaning: '成功' },
  { word: 'effort', meaning: '努力' },
  { word: 'believe', meaning: '相信' },
  { word: 'support', meaning: '支持' },
  { word: 'encourage', meaning: '鼓励' },
  { word: 'opportunity', meaning: '机会' },
  { word: 'quality', meaning: '质量' },
  { word: 'process', meaning: '过程' },
  { word: 'method', meaning: '方法' },
  { word: 'problem', meaning: '问题' },
  { word: 'solution', meaning: '解决' },
  { word: 'team', meaning: '团队' },
  { word: 'project', meaning: '项目' },
  { word: 'result', meaning: '结果' },
  { word: 'goal', meaning: '目标' },
  { word: 'knowledge', meaning: '知识' },
  { word: 'skill', meaning: '技能' },
  { word: 'experience', meaning: '经验' },
  { word: 'confidence', meaning: '信心' },
  { word: 'hope', meaning: '希望' },
  { word: 'dream', meaning: '梦想' },
  { word: 'future', meaning: '未来' },
  { word: 'journey', meaning: '旅程' },
  { word: 'story', meaning: '故事' },
  { word: 'moment', meaning: '时刻' },
  { word: 'feeling', meaning: '感受' },
  { word: 'thought', meaning: '想法' },
  { word: 'idea', meaning: '想法' },
  { word: 'change', meaning: '改变' },
  { word: 'growth', meaning: '成长' },
  { word: 'value', meaning: '价值' },
  { word: 'power', meaning: '力量' },
  { word: 'meaning', meaning: '意义' },
  { word: 'spirit', meaning: '精神' },
  { word: 'heart', meaning: '心' },
  { word: 'mind', meaning: '心智' },
  { word: 'attention', meaning: '注意' },
  { word: 'interest', meaning: '兴趣' },
  { word: 'energy', meaning: '能量' },
  { word: 'passion', meaning: '热情' },
  { word: 'purpose', meaning: '目的' },
  { word: 'courage', meaning: '勇气' },
  { word: 'respect', meaning: '尊重' },
  { word: 'trust', meaning: '信任' },
  { word: 'relationship', meaning: '关系' },
  { word: 'communication', meaning: '沟通' },
  { word: 'understanding', meaning: '理解' }
];

console.log('Vocabulary helper script created');
console.log('Total vocab words available:', vocabList.length);
